# Generated by Django 5.0.2 on 2024-02-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=300)),
                ('Department', models.CharField(max_length=300)),
                ('DateOfJoining', models.DateTimeField(auto_now_add=True)),
                ('PhotoFileName', models.CharField(max_length=300)),
            ],
        ),
    ]
