# Generated by Django 5.0.2 on 2024-02-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_alter_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
